export const ROUTES = {
  home: "/",
  login: "/login",
  register: "/register",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  verifyEmail: "/verify-email",
  feed: "/feed",
  professional: "/professionals",
  clientDashboard: "/dashboard",
  dashboardRequests: "/dashboard/requests",
  dashboardRequestsNew: "/dashboard/requests/new",
  dashboardFavorites: "/dashboard/favorites",
  dashboardMessages: "/dashboard/messages",
  dashboardSaved: "/dashboard/saved",
  dashboardNotifications: "/dashboard/notifications",
  dashboardSettings: "/dashboard/settings",
  professionalDashboard: "/pro/dashboard",
  proDashboardProfile: "/pro/dashboard/profile",
  proDashboardServices: "/pro/dashboard/services",
  proDashboardPortfolio: "/pro/dashboard/portfolio",
  proDashboardCertificates: "/pro/dashboard/certificates",
  proDashboardMessages: "/pro/dashboard/messages",
  proDashboardSaved: "/pro/dashboard/saved",
  proDashboardNotifications: "/pro/dashboard/notifications",
  proDashboardSettings: "/pro/dashboard/settings",
  admin: "/admin",
} as const;
